---
builders:
- accelerator: kvm
  boot_command:
  - "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"
  boot_wait: 5s
  disk_interface: virtio
  disk_size: 5000
  format: qcow2
  headless: true
  http_directory: httpdir
  http_port_max: 10089
  http_port_min: 10082
  iso_checksum: "{{user `iso_checksum`}}"
  iso_checksum_type: "{{user `iso_checksum_type`}}"
  iso_url: "{{user `iso_url`}}"
  net_device: virtio-net
  shutdown_command: shutdown -P now
  ssh_host_port_max: 2229
  ssh_host_port_min: 2222
  ssh_password: "{{user `ssh_password`}}"
  ssh_port: 22
  ssh_username: "{{user `ssh_username`}}"
  ssh_wait_timeout: 30s
  type: qemu-iso
  vm_name: "{{user `vm_name`}}"
post-processors:
- - keep_input_artifact: false
    override:
      qemu:
        output: "{{user `vm_name`}}-qemu.box"
    type: vagrant
  - artifact: "{{user `atlas_username`}}/{{user `atlas_name`}}"
    artifact_type: vagrant.box
    metadata:
      provider: qemu
      version: "{{user `version`}}"
    only:
    - qemu-iso
    type: atlas
provisioners:
- execute_command: echo 'vagrant'|sudo -S sh '{{.Path}}'
  override:
    qemu-iso:
      scripts:
      - scripts/base.sh
      - scripts/vagrant.sh
      - scripts/virtualbox.sh
      - scripts/cleanup.sh
  type: shell
variables:
  atlas_name: "{{env `ATLAS_NAME`}}"
  atlas_username: "{{env `ATLAS_USERNAME`}}"
  disk_size: "{{env `DISK_SIZE`}}"
  guest_os_type: "{{env `GUEST_OS_TYPE`}}"
  iso_checksum: "{{env `ISO_CHECKSUM`}}"
  iso_checksum_type: "{{env `ISO_CHECKSUM_TYPE`}}"
  iso_url: "{{env `ISO_URL`}}"
  mem_size: "{{env `MEM_SIZE`}}"
  numvcpus: "{{env `NUMVCPUS`}}"
  ssh_password: "{{env `SSH_PASSWORD`}}"
  ssh_username: "{{env `SSH_USERNAME`}}"
  version: "{{env `VMVERSION`}}"
  vm_name: "{{env `VM_NAME`}}"
