atlas_name: "centos-7-2-min"
atlas_username: "devopco"
disk_size: "10000"
guest_os_type: "RedHat_64"
iso_checksum: "f90e4d28fa377669b2db16cbcb451fcb9a89d2460e3645993e30e137ac37d284"
iso_checksum_type: "sha256"
iso_url: "http://mirrors.seas.harvard.edu/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso"
mem_size: "2048"
numvcpus: "2"
ssh_password: "vagrant"
ssh_username: "vagrant"
version: "0.0.1"
vm_name: "centos-7-2-min"
